// GENERATED by scripts/gen-protocol.mjs from sugar-crush/docs/protocol/sugarcrush.v1.schema.json — do not edit.
// Run `npm run gen:protocol` after the server protocol changes.

/** The protocol major this client speaks (`server.hello` min/max). */
export const PROTOCOL = 1 as const

export type Scope = 'read' | 'write' | 'approve' | 'admin'

export interface Admission {
  admitted: "started" | "queued" | "steered" | "pending"
  turnId?: string
  messageId?: string
  steerId?: string
  queuePosition?: number
  queueId?: string
}

export interface Error {
  code: number
  message: string
  data: {
    kind: string
    retryable?: boolean
    retryAfterMs?: number
  }
}

export interface EventEnvelope {
  sessionId: SessionId | null
  /** Durable session events only; gap-free per session. */
  seq?: number
  type: string
  /** Milliseconds since the epoch. */
  ts: number
  turnId?: string
  durable: boolean
  data: Record<string, unknown>
}

export interface MemoryEntry {
  id: string
  type?: string
  tags?: string[]
  scope: "user" | "project" | "agent"
  content: string
  createdAt?: string
  modifiedAt?: string
}

export interface PendingAsk {
  askId: string
  toolCallId: string
  tool: string
  arguments: Record<string, unknown>
  reason?: string
  /** `gate`, or `hook:<names>` */
  source?: string
  mode?: string
  options: ("once" | "always" | "reject")[]
  alwaysScope?: Record<string, string>
}

export type PermissionMode = "default" | "accept-edits" | "plan" | "auto" | "dont-ask" | "bypass-permissions"

export interface QueueEntry {
  queueId: string
  text: string
  position: number
}

/** A session id: letters, digits, ".", "_" and "-". */
export type SessionId = string

export interface SessionSnapshot {
  sessionId: SessionId
  status: "idle" | "busy" | "waiting_permission"
  turnId?: string
  /** Transcript rows, as they are saved. */
  messages: Record<string, unknown>[]
  queued?: string[]
  spentUsd?: number
  lastSeq: number
  permissionMode?: PermissionMode | null
  pendingAsks: PendingAsk[]
  queue: QueueEntry[]
  subagents?: Record<string, unknown>[]
}

export interface SessionSummary {
  id: SessionId
  name?: string | null
  provider?: string | null
  model?: string | null
  kind?: string | null
  parentId?: string | null
  createdAt?: string | null
  updatedAt?: string | null
  turns?: number | null
  preview?: string | null
  open: boolean
  status: "closed" | "idle" | "busy" | "waiting_permission"
  permissionMode?: PermissionMode | null
  spentUsd?: number | null
}

export type Subscription = {
  reset: true
  snapshot: SessionSnapshot
  throughSeq: number
  pendingAsks: PendingAsk[]
} | {
  fromSeq: number
  throughSeq: number
  pendingAsks: PendingAsk[]
}

export interface Usage {
  totalTokens?: number
  inputTokens?: number | null
  outputTokens?: number | null
  cacheReadTokens?: number | null
  cacheCreationTokens?: number | null
  reasoningTokens?: number | null
  costUsd?: number
}

/** Every method: its params and its result. */
export interface Methods {
  /** The agents a turn can delegate to. */
  "agents.list": {
    params: Record<string, unknown>
    result: {
      items: {
        name: string
        description?: string
        model?: string
        provider?: string
        permissionMode?: PermissionMode
        active?: boolean
      }[]
    }
  }
  /** The sub-agents a session's turns have delegated to, with their latest activity. */
  "agents.subtree": {
    params: {
      sessionId: SessionId
    }
    result: {
      items: Record<string, unknown>[]
    }
  }
  /** The background sessions this server supervises. */
  "bg.list": {
    params: Record<string, unknown>
    result: {
      items: Record<string, unknown>[]
    }
  }
  /** A background session's output from an offset. */
  "bg.output": {
    params: {
      bgId: string
      offset?: number
      limit?: number
    }
    result: {
      bgId: string
      offset: number
      text: string
      total: number
      status: string
    }
  }
  /** Stop a background session. */
  "bg.stop": {
    params: {
      bgId: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      bgId: string
      outcome: string
    }
  }
  /** Say which sessions this client shows, and which is in front. */
  "client.viewing": {
    params: {
      sessionIds?: SessionId[]
      foreground?: SessionId | null
    }
    result: Record<string, unknown>
  }
  /** Run a slash command in a session (command files, and the built-ins that run headless). */
  "command.exec": {
    params: {
      sessionId: SessionId
      name: string
      args?: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: Admission | {
      rows: {
        role: string
        content: string
        uiOnly: boolean
      }[]
      effects: string[]
    }
  }
  /** The slash commands a session knows, and where each runs. */
  "command.list": {
    params: {
      sessionId?: SessionId
    }
    result: {
      items: ({
        name: string
        description?: string
        argumentHint?: string | null
        source: "builtin" | "file"
        runsIn: "server" | "client"
      })[]
    }
  }
  /** The workspace's changed and untracked files. */
  "files.changed": {
    params: Record<string, unknown>
    result: {
      items: ({
        path: string
        status: string
        from?: string | null
      })[]
      truncated: boolean
    }
  }
  /** The workspace's uncommitted changes to tracked files, as a unified diff. */
  "files.diff": {
    params: {
      ref?: string
    }
    result: {
      ref: string
      diff: string
      truncated: boolean
    }
  }
  /** A file under the project root, read-only and size-capped. */
  "files.read": {
    params: {
      path: string
      offset?: number
      limit?: number
    }
    result: {
      path: string
      size: number
      offset: number
      binary: boolean
      content: string
      truncated: boolean
    }
  }
  /** Add a note. */
  "memory.add": {
    params: {
      content: string
      scope?: "user" | "project" | "agent"
      tags?: string[]
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      id: string
    }
  }
  /** Delete a note. */
  "memory.delete": {
    params: {
      id: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      deleted: boolean
    }
  }
  /** Replace a note's text. */
  "memory.edit": {
    params: {
      id: string
      content: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      id: string
    }
  }
  /** The notes of one memory scope. */
  "memory.list": {
    params: {
      scope?: "user" | "project" | "agent"
    }
    result: {
      items: MemoryEntry[]
    }
  }
  /** Notes matching a query, best first, across every scope. */
  "memory.search": {
    params: {
      query: string
      limit?: number
    }
    result: {
      items: MemoryEntry[]
    }
  }
  /** The questions still open, for one session or all open sessions. */
  "permission.pending": {
    params: {
      sessionId?: SessionId
    }
    result: {
      items: PendingAsk[]
    }
  }
  /** Answer an open permission question; the first answer wins. */
  "permission.respond": {
    params: {
      sessionId: SessionId
      askId: string
      reply: "once" | "always" | "reject"
      note?: string
      cascade?: boolean
      remember?: "session" | "project" | "user"
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      applied: boolean
      askId: string
      reply?: "once" | "always" | "reject" | null
      cascaded: string[]
    }
  }
  /** The effective permission mode and rules, read-only. */
  "permission.rules": {
    params: {
      sessionId?: SessionId
    }
    result: {
      mode: PermissionMode | null
      modeSource?: string | null
      rules: {
        pattern: string
        action: string
      }[]
      sessionGrants: string[]
    }
  }
  /** Liveness and load. */
  "server.health": {
    params: Record<string, unknown>
    result: {
      ok: boolean
      version: string
      uptimeS: number
      sessionsOpen: number
      turnsRunning: number
      draining: boolean
    }
  }
  /** The handshake: protocol version, features, limits; optionally resume subscriptions. */
  "server.hello": {
    params: {
      minProtocol?: number
      maxProtocol?: number
      client?: {
        name?: string
        version?: string
        instanceId?: string
      }
      caps?: string[]
      /** sessionId => the last seq the client holds */
      resume?: Record<string, number>
    }
    result: {
      protocol: number
      server: {
        version: string
        connectionId: string
        root?: string | null
        pid?: number | null
      }
      features: {
        methods: string[]
        events: string[]
      }
      limits: Record<string, number>
      principal: {
        kind: string
        via?: string
        scopes: ("read" | "write" | "approve" | "admin")[]
      }
      defaults: {
        permissionMode?: PermissionMode
      }
      resumed: Record<string, Subscription | {
        error: string
      }>
    }
  }
  /** What this server offers: providers, agents, commands, tools, permission modes. */
  "server.info": {
    params: Record<string, unknown>
    result: {
      version: string
      protocol: number
      root?: string | null
      providers?: string[]
      agents?: {
        name: string
        description?: string
      }[]
      tools?: string[]
      commands?: string[]
      permissionModes: PermissionMode[]
      defaultPermissionMode: PermissionMode
      limits?: Record<string, number>
    }
  }
  /** Stop the server, draining running turns first. */
  "server.shutdown": {
    params: {
      drainSeconds?: number
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      accepted: boolean
    }
  }
  /** Cancel the running turn (hard, or soft at the next step boundary). */
  "session.cancel": {
    params: {
      sessionId: SessionId
      turnId?: string
      mode?: "hard" | "soft"
      clearQueue?: boolean
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      cancelled: boolean
      mode: "hard" | "soft"
      cleared: number
    }
  }
  /** Release a session (refused while a turn runs unless force). */
  "session.close": {
    params: {
      sessionId: SessionId
      force?: boolean
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      closed: boolean
    }
  }
  /** Create a session and open it. */
  "session.create": {
    params: {
      name?: string
      permissionMode?: PermissionMode
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: SessionSummary
  }
  /** Delete a session and its history. */
  "session.delete": {
    params: {
      sessionId: SessionId
      force?: boolean
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      deleted: SessionId[]
    }
  }
  /** Remove a queued prompt. */
  "session.dequeue": {
    params: {
      sessionId: SessionId
      queueId: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      dequeued: boolean
    }
  }
  /** A session's transcript as markdown, json or text. */
  "session.export": {
    params: {
      sessionId: SessionId
      format?: "markdown" | "json" | "text"
    }
    result: {
      format: "markdown" | "json" | "text"
      content: string
    }
  }
  /** Branch a session into a new one carrying its transcript. */
  "session.fork": {
    params: {
      sessionId: SessionId
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: SessionSummary
  }
  /** A session's snapshot: rows, status, queue, open questions, usage. */
  "session.get": {
    params: {
      sessionId: SessionId
    }
    result: SessionSnapshot
  }
  /** The workspace's sessions, newest activity first, paged. */
  "session.list": {
    params: {
      limit?: number
      cursor?: SessionId
      query?: string
    }
    result: {
      items: SessionSummary[]
      nextCursor: string | null
    }
  }
  /** The prompts queued behind the running turn. */
  "session.queue": {
    params: {
      sessionId: SessionId
    }
    result: {
      items: QueueEntry[]
    }
  }
  /** Rename a session. */
  "session.rename": {
    params: {
      sessionId: SessionId
      name: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: SessionSummary
  }
  /** Send a prompt: start a turn, or queue / steer / interrupt the running one. */
  "session.send": {
    params: {
      sessionId: SessionId
      text: string
      delivery?: "queue" | "steer" | "interrupt"
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: Admission
  }
  /** The permission mode the session's next turns run in. */
  "session.setMode": {
    params: {
      sessionId: SessionId
      permissionMode: PermissionMode
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      permissionMode: PermissionMode
    }
  }
  /** Follow a session's events from a cursor (replay) or from a snapshot. */
  "session.subscribe": {
    params: {
      sessionId: SessionId
      afterSeq?: number
      mode?: "full" | "narration"
    }
    result: Subscription
  }
  /** Stop following a session. */
  "session.unsubscribe": {
    params: {
      sessionId: SessionId
    }
    result: {
      unsubscribed: boolean
    }
  }
  /** Effective values and where each came from, or one tier's file; secrets masked. */
  "settings.get": {
    params: {
      scope?: "effective" | "user" | "project"
    }
    result: {
      scope: "effective" | "user" | "project"
      values: Record<string, unknown>
    }
  }
  /** Every setting: type, default, help, and whether a client may write it. */
  "settings.schema": {
    params: Record<string, unknown>
    result: {
      items: {
        key: string
        type: string
        default?: unknown
        group: string
        label: string
        help?: string
        enum?: unknown[]
        min?: number
        max?: number
        riskClass: string
        applies: string
        projectSettable?: boolean
        sensitive: boolean
        writableRemotely: boolean
      }[]
    }
  }
  /** Write an allowlisted setting to the user tier or a trusted project. */
  "settings.set": {
    params: {
      key: string
      value?: unknown
      scope?: "user" | "project"
      reset?: boolean
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      key: string
      scope: string
      written: string
      applies?: string
    }
  }
  /** A session's todo list, as its Todo tool last wrote it. */
  "todo.get": {
    params: {
      sessionId: SessionId
    }
    result: {
      items: ({
        content: string
        status: "pending" | "in_progress" | "completed" | "cancelled"
      })[]
    }
  }
  /** A finished tool call's full output, from an offset. */
  "tool.output": {
    params: {
      sessionId: SessionId
      toolCallId: string
      offset?: number
      limit?: number
    }
    result: {
      toolCallId: string
      offset: number
      content: string
      total: number
      isError: boolean
      more: boolean
    }
  }
}

export type MethodName = keyof Methods
export type MethodParams<M extends MethodName> = Methods[M]['params']
export type MethodResult<M extends MethodName> = Methods[M]['result']

/** The scope each method needs. */
export const METHOD_SCOPES: { readonly [M in MethodName]: Scope } = {
  "agents.list": "read",
  "agents.subtree": "read",
  "bg.list": "read",
  "bg.output": "read",
  "bg.stop": "write",
  "client.viewing": "read",
  "command.exec": "write",
  "command.list": "read",
  "files.changed": "read",
  "files.diff": "read",
  "files.read": "read",
  "memory.add": "write",
  "memory.delete": "write",
  "memory.edit": "write",
  "memory.list": "read",
  "memory.search": "read",
  "permission.pending": "read",
  "permission.respond": "approve",
  "permission.rules": "read",
  "server.health": "read",
  "server.hello": "read",
  "server.info": "read",
  "server.shutdown": "admin",
  "session.cancel": "write",
  "session.close": "write",
  "session.create": "write",
  "session.delete": "write",
  "session.dequeue": "write",
  "session.export": "read",
  "session.fork": "write",
  "session.get": "read",
  "session.list": "read",
  "session.queue": "read",
  "session.rename": "write",
  "session.send": "write",
  "session.setMode": "write",
  "session.subscribe": "read",
  "session.unsubscribe": "read",
  "settings.get": "read",
  "settings.schema": "read",
  "settings.set": "admin",
  "todo.get": "read",
  "tool.output": "read",
}

/** The methods that accept an `idempotencyKey`. */
export const IDEMPOTENT_METHODS: readonly MethodName[] = [
  "bg.stop",
  "command.exec",
  "memory.add",
  "memory.delete",
  "memory.edit",
  "permission.respond",
  "server.shutdown",
  "session.cancel",
  "session.close",
  "session.create",
  "session.delete",
  "session.dequeue",
  "session.fork",
  "session.rename",
  "session.send",
  "session.setMode",
  "settings.set",
]

/** Every event type: the shape of its `data`. */
export interface Events {
  /** The reply, complete; repairs any delta a client dropped. */
  "assistant.completed": {
    messageId?: string
    ref?: number
    content: string
    reasoning?: string
    lengthStopped: boolean
    stepsTruncated: boolean
    usage?: Usage
  }
  /** Streamed reply text. */
  "assistant.delta": {
    text: string
    partId: string
    /** Byte offset into the part; a gap means a delta was dropped. */
    offset: number
  }
  /** The tail of the reply so far, at most every 2 s, for narration subscriptions. */
  "assistant.narration": {
    partId: string
    tail: string
  }
  /** The history was compacted before a turn. */
  "compaction.completed": {
    kind: "llm" | "heuristic" | "truncate"
    before: number
    after: number
    savedPct?: number
  }
  /** A transcript row was added: the prompt, a notice, a summary. */
  "message.created": {
    messageId: string
    ref?: number
    role: string
    kind?: string
    content: string
    createdAt?: number
  }
  /** A tool call is waiting for an answer (permission.respond). */
  "permission.requested": PendingAsk
  /** A question was answered or cancelled. */
  "permission.resolved": {
    askId: string
    reply?: "once" | "always" | "reject"
    note?: string
    cancelled?: boolean
  }
  /** Streamed reasoning text. */
  "reasoning.delta": {
    text: string
    partId: string
    /** Byte offset into the part; a gap means a delta was dropped. */
    offset: number
  }
  /** This client fell behind; ephemeral events were dropped — resubscribe. */
  "server.overflow": {
    dropped: number
    action: "resubscribe"
  }
  /** The server is stopping. */
  "server.shutdown": {
    reason: string
    graceSeconds: number
  }
  /** Liveness, every tickIntervalMs. */
  "server.tick": {
    now: number
    turnsRunning: number
  }
  /** A session was created. */
  "session.created": SessionSummary
  /** A session was deleted. */
  "session.deleted": {
    id: SessionId
  }
  /** The session became idle, busy or waiting_permission. */
  "session.status": {
    status: "idle" | "busy" | "waiting_permission"
  }
  /** A session was renamed or its mode changed. */
  "session.updated": SessionSummary
  /** The session spend cap stopped the turn. */
  "spend_cap.breached": {
    calls: number
    spent: number
    cap: number
  }
  /** A delegated sub-agent finished. */
  "subagent.finished": {
    id: string
    op: string
    name?: string | null
    task?: string | null
    parentCallId?: string | null
    tail?: unknown
    outcome?: unknown
  }
  /** A delegated sub-agent made progress. */
  "subagent.progress": {
    id: string
    op: string
    name?: string | null
    task?: string | null
    parentCallId?: string | null
    tail?: unknown
    outcome?: unknown
  }
  /** A delegated sub-agent started. */
  "subagent.started": {
    id: string
    op: string
    name?: string | null
    task?: string | null
    parentCallId?: string | null
    tail?: unknown
    outcome?: unknown
  }
  /** A tool call finished (content capped; tool.output has the rest). */
  "tool.finished": {
    messageId?: string
    ref?: number
    toolCallId: string
    name: string
    isError: boolean
    durationMs?: number
    /** At most 256 KiB; tool.output reads the rest. */
    content: string
    truncated?: boolean
    diff?: string
    denial?: {
      kind: string
      reason?: string
    }
    replaces?: string
  }
  /** A tool call started. */
  "tool.started": {
    messageId?: string
    ref?: number
    toolCallId: string
    name: string
    arguments?: Record<string, unknown>
  }
  /** A turn ended, with its stopReason. */
  "turn.completed": {
    stopReason: "end_turn" | "max_steps" | "length" | "cancelled" | "spend_cap" | "error"
    error?: string
    messageId?: string
  }
  /** A queued prompt left the queue (sent or removed). */
  "turn.dequeued": {
    queueId: string
    text?: string
    reason: "sent" | "removed"
  }
  /** A prompt was queued behind the running turn. */
  "turn.queued": {
    queueId: string
    text: string
    position: number
  }
  /** A turn began. */
  "turn.started": {
    turnId: string
    messageId?: string
  }
  /** A steering message was handed to the running turn. */
  "turn.steered": {
    turnId?: string
    steerId: string
  }
  /** The running turn reached a step boundary. */
  "turn.step": {
    step: number
    maxSteps: number
    context?: Record<string, unknown> | null
  }
  /** Token and cost usage changed. */
  "usage.updated": {
    step: number
    usage?: Usage | null
    turnUsage?: Usage | null
  }
}

export type EventName = keyof Events

/** Whether each event type is durable (logged, carries a `seq`) and its scope. */
export const EVENT_KINDS: { readonly [E in EventName]: { readonly durable: boolean; readonly scope: 'session' | 'server' } } = {
  "assistant.completed": { durable: true, scope: "session" },
  "assistant.delta": { durable: false, scope: "session" },
  "assistant.narration": { durable: false, scope: "session" },
  "compaction.completed": { durable: true, scope: "session" },
  "message.created": { durable: true, scope: "session" },
  "permission.requested": { durable: true, scope: "session" },
  "permission.resolved": { durable: true, scope: "session" },
  "reasoning.delta": { durable: false, scope: "session" },
  "server.overflow": { durable: false, scope: "server" },
  "server.shutdown": { durable: false, scope: "server" },
  "server.tick": { durable: false, scope: "server" },
  "session.created": { durable: false, scope: "server" },
  "session.deleted": { durable: false, scope: "server" },
  "session.status": { durable: true, scope: "session" },
  "session.updated": { durable: false, scope: "server" },
  "spend_cap.breached": { durable: true, scope: "session" },
  "subagent.finished": { durable: true, scope: "session" },
  "subagent.progress": { durable: false, scope: "session" },
  "subagent.started": { durable: true, scope: "session" },
  "tool.finished": { durable: true, scope: "session" },
  "tool.started": { durable: true, scope: "session" },
  "turn.completed": { durable: true, scope: "session" },
  "turn.dequeued": { durable: true, scope: "session" },
  "turn.queued": { durable: true, scope: "session" },
  "turn.started": { durable: true, scope: "session" },
  "turn.steered": { durable: true, scope: "session" },
  "turn.step": { durable: false, scope: "session" },
  "usage.updated": { durable: true, scope: "session" },
}
