// GENERATED by scripts/gen-protocol.mjs from sugar-crush/docs/protocol/sugarcrush.v1.schema.json — do not edit.
// Run `npm run gen:protocol` after the server protocol changes.

/** The protocol major this client speaks (`server.hello` min/max). */
export const PROTOCOL = 1 as const

export type Scope = 'read' | 'write' | 'approve' | 'admin'

export interface Admission {
  admitted: "started" | "queued" | "steered" | "pending"
  turnId?: string
  messageId?: string
  steerId?: string
  queuePosition?: number
  queueId?: string
}

/** A background (/bg) session; never its output. */
export interface BackgroundSession {
  bgId: string
  name: string
  task: string
  status: "pending" | "running" | "streaming" | "stalled" | "completed" | "failed" | "stopped" | "timed_out"
  agent?: string
  model?: string
  tags?: string[]
  workingDirectory?: string
  createdAt: string
  completedAt?: string | null
  tokensUsed?: number
  costUsd?: number
  error?: string | null
  /** bg.output reads the output itself, from an offset. */
  outputBytes: number
  /** The stored session a /fork session continues; null for /bg. */
  forkedSessionId?: string | null
  /** Re-adopted at boot from an earlier server or TUI. */
  adopted: boolean
}

export interface Error {
  code: number
  message: string
  data: {
    kind: string
    retryable?: boolean
    retryAfterMs?: number
  }
}

export interface EventEnvelope {
  sessionId: SessionId | null
  /** Durable session events only; gap-free per session. */
  seq?: number
  type: string
  /** Milliseconds since the epoch. */
  ts: number
  turnId?: string
  durable: boolean
  data: Record<string, unknown>
  /** Set by the serve gateway on an event relayed from another project root's workspace host (roadmap O-7). */
  root?: string
}

export interface MemoryEntry {
  id: string
  type?: string
  tags?: string[]
  scope: "user" | "project" | "agent"
  content: string
  createdAt?: string
  modifiedAt?: string
}

export interface PendingAsk {
  askId: string
  toolCallId: string
  tool: string
  arguments: Record<string, unknown>
  reason?: string
  /** `gate`, `hook:<names>`, or `tool:<name>` for a question the call puts itself (`AskUser`, `PlanExit`) */
  source?: string
  mode?: string
  options: ("once" | "always" | "reject")[]
  alwaysScope?: Record<string, string>
  /** The delegated run that asked, when a sub-agent's question was relayed; absent for the turn's own. */
  origin?: {
    agentId: string
    agentName?: string
    parentCallId?: string
  }
}

export type PermissionMode = "default" | "accept-edits" | "plan" | "auto" | "dont-ask" | "bypass-permissions"

export interface QueueEntry {
  queueId: string
  text: string
  position: number
}

/** A session id: letters, digits, ".", "_" and "-". */
export type SessionId = string

export interface SessionSnapshot {
  sessionId: SessionId
  status: "idle" | "busy" | "waiting_permission"
  turnId?: string
  /** Transcript rows, as they are saved. */
  messages: Record<string, unknown>[]
  queued?: string[]
  spentUsd?: number
  lastSeq: number
  permissionMode?: PermissionMode | null
  pendingAsks: PendingAsk[]
  queue: QueueEntry[]
  subagents?: Record<string, unknown>[]
}

export interface SessionSummary {
  id: SessionId
  name?: string | null
  provider?: string | null
  model?: string | null
  kind?: string | null
  parentId?: string | null
  createdAt?: string | null
  updatedAt?: string | null
  turns?: number | null
  preview?: string | null
  open: boolean
  status: "closed" | "idle" | "busy" | "waiting_permission"
  permissionMode?: PermissionMode | null
  spentUsd?: number | null
  /** Set by the serve gateway on a session another project root's workspace host answered for (roadmap O-7). */
  root?: string
}

export type Subscription = {
  reset: true
  snapshot: SessionSnapshot
  throughSeq: number
  pendingAsks: PendingAsk[]
} | {
  fromSeq: number
  throughSeq: number
  pendingAsks: PendingAsk[]
}

export interface Usage {
  totalTokens?: number
  inputTokens?: number | null
  outputTokens?: number | null
  cacheReadTokens?: number | null
  cacheCreationTokens?: number | null
  reasoningTokens?: number | null
  costUsd?: number
}

/** Every method: its params and its result. */
export interface Methods {
  /** Cancel, pause, resume or background a delegated run. */
  "agents.control": {
    params: {
      sessionId: SessionId
      /** A delegated run's id, as its `subagent.*` events name it. */
      agentId: string
      verb: "cancel" | "pause" | "resume" | "background"
      /** What a resumed FINISHED run is told; the default asks it to continue. */
      text?: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      agentId: string
      /** queued: in the running run's mailbox, read at its next step; resuming: a finished run is being continued. */
      status: "queued" | "resuming"
      msgId?: string
    }
  }
  /** The agents a turn can delegate to. */
  "agents.list": {
    params: Record<string, unknown>
    result: {
      items: {
        name: string
        description?: string
        model?: string
        provider?: string
        permissionMode?: PermissionMode
        active?: boolean
      }[]
    }
  }
  /** Message a delegated run: into its mailbox while it runs, as a follow-up once it finished. */
  "agents.message": {
    params: {
      sessionId: SessionId
      /** A delegated run's id, as its `subagent.*` events name it. */
      agentId: string
      text: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      agentId: string
      /** queued: in the running run's mailbox, read at its next step; resuming: a finished run is being continued. */
      status: "queued" | "resuming"
      msgId?: string
    }
  }
  /** The sub-agents a session's turns have delegated to, with their latest activity. */
  "agents.subtree": {
    params: {
      sessionId: SessionId
    }
    result: {
      items: Record<string, unknown>[]
    }
  }
  /** A delegated run's own transcript, read from a byte offset. */
  "agents.transcript": {
    params: {
      sessionId: SessionId
      /** A delegated run's id, as its `subagent.*` events name it. */
      agentId: string
      offset?: number
      limit?: number
    }
    result: {
      agentId: string
      /** Where the next page starts: just past the last whole line read. */
      offset: number
      items: ({
        t: "user" | "assistant" | "tool_call" | "tool_result" | "thinking" | "inbox" | "status"
        ts?: number
        text?: string
        callId?: string
        tool?: string
        args?: Record<string, unknown>
        ok?: boolean
        content?: string
        truncated?: boolean
        status?: string
        outcome?: string
        error?: string
        from?: string
        mode?: string
        msgId?: string
        step?: number
      })[]
      more: boolean
      finished: boolean
    }
  }
  /** Send a settled background session's result into a session as a prompt. */
  "bg.inject": {
    params: {
      sessionId: SessionId
      bgId: string
      delivery?: "queue" | "steer" | "interrupt"
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      bgId: string
      sessionId: SessionId
      admitted: "started" | "queued" | "steered" | "pending"
      turnId?: string
      messageId?: string
      steerId?: string
      queuePosition?: number
      queueId?: string
    }
  }
  /** The background sessions this server supervises, running and settled. */
  "bg.list": {
    params: Record<string, unknown>
    result: {
      items: BackgroundSession[]
    }
  }
  /** A background session's output from an offset. */
  "bg.output": {
    params: {
      bgId: string
      offset?: number
      limit?: number
    }
    result: {
      bgId: string
      offset: number
      text: string
      total: number
      status: string
    }
  }
  /** Start a background session on a task, as /bg does. */
  "bg.spawn": {
    params: {
      task: string
      agent?: string
      name?: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: BackgroundSession
  }
  /** Stop a background session. */
  "bg.stop": {
    params: {
      bgId: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      bgId: string
      outcome: string
    }
  }
  /** Say which sessions this client shows, and which is in front. */
  "client.viewing": {
    params: {
      sessionIds?: SessionId[]
      foreground?: SessionId | null
      /** Narrate every followed session that is not in front, instead of streaming it. */
      narrate?: boolean
    }
    result: {
      /** The followed sessions this client now hears as narration. */
      narrated: SessionId[]
    }
  }
  /** Run a slash command in a session (command files, and the built-ins that run headless). */
  "command.exec": {
    params: {
      sessionId: SessionId
      name: string
      args?: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: Admission | {
      rows: {
        role: string
        content: string
        uiOnly: boolean
      }[]
      effects: string[]
    }
  }
  /** The slash commands a session knows, and where each runs. */
  "command.list": {
    params: {
      sessionId?: SessionId
    }
    result: {
      items: ({
        name: string
        description?: string
        argumentHint?: string | null
        source: "builtin" | "file"
        runsIn: "server" | "client"
      })[]
    }
  }
  /** The workspace's changed and untracked files. */
  "files.changed": {
    params: Record<string, unknown>
    result: {
      items: ({
        path: string
        status: string
        from?: string | null
      })[]
      truncated: boolean
    }
  }
  /** The workspace's uncommitted changes to tracked files, as a unified diff. */
  "files.diff": {
    params: {
      ref?: string
    }
    result: {
      ref: string
      diff: string
      truncated: boolean
    }
  }
  /** A file under the project root, read-only and size-capped. */
  "files.read": {
    params: {
      path: string
      offset?: number
      limit?: number
    }
    result: {
      path: string
      size: number
      offset: number
      binary: boolean
      content: string
      truncated: boolean
    }
  }
  /** Add a note. */
  "memory.add": {
    params: {
      content: string
      scope?: "user" | "project" | "agent"
      tags?: string[]
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      id: string
    }
  }
  /** Delete a note. */
  "memory.delete": {
    params: {
      id: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      deleted: boolean
    }
  }
  /** Replace a note's text. */
  "memory.edit": {
    params: {
      id: string
      content: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      id: string
    }
  }
  /** The notes of one memory scope. */
  "memory.list": {
    params: {
      scope?: "user" | "project" | "agent"
    }
    result: {
      items: MemoryEntry[]
    }
  }
  /** Notes matching a query, best first, across every scope. */
  "memory.search": {
    params: {
      query: string
      limit?: number
    }
    result: {
      items: MemoryEntry[]
    }
  }
  /** The questions still open, for one session or all open sessions. */
  "permission.pending": {
    params: {
      sessionId?: SessionId
    }
    result: {
      items: PendingAsk[]
    }
  }
  /** Answer an open permission question; the first answer wins. */
  "permission.respond": {
    params: {
      sessionId: SessionId
      askId: string
      reply: "once" | "always" | "reject"
      note?: string
      cascade?: boolean
      remember?: "session" | "project" | "user"
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      applied: boolean
      askId: string
      reply?: "once" | "always" | "reject" | null
      cascaded: string[]
    }
  }
  /** The effective permission mode and rules, read-only. */
  "permission.rules": {
    params: {
      sessionId?: SessionId
    }
    result: {
      mode: PermissionMode | null
      modeSource?: string | null
      rules: {
        pattern: string
        action: string
      }[]
      sessionGrants: string[]
    }
  }
  /** Liveness and load. */
  "server.health": {
    params: Record<string, unknown>
    result: {
      ok: boolean
      version: string
      uptimeS: number
      sessionsOpen: number
      turnsRunning: number
      draining: boolean
    }
  }
  /** The handshake: protocol version, features, limits; optionally resume subscriptions. */
  "server.hello": {
    params: {
      minProtocol?: number
      maxProtocol?: number
      client?: {
        name?: string
        version?: string
        instanceId?: string
      }
      caps?: string[]
      /** sessionId => the last seq the client holds */
      resume?: Record<string, number>
    }
    result: {
      protocol: number
      server: {
        version: string
        connectionId: string
        root?: string | null
        pid?: number | null
      }
      features: {
        methods: string[]
        events: string[]
      }
      limits: Record<string, number>
      principal: {
        kind: string
        via?: string
        scopes: ("read" | "write" | "approve" | "admin")[]
      }
      defaults: {
        permissionMode?: PermissionMode
        /** The delivery a client should offer first for a prompt sent while a turn runs: the `queueMode` setting, `steer` unless set. A `session.send` that names none still queues. */
        delivery?: "queue" | "steer" | "interrupt"
      }
      resumed: Record<string, Subscription | {
        error: string
      }>
    }
  }
  /** What this server offers: providers, agents, commands, tools, permission modes. */
  "server.info": {
    params: Record<string, unknown>
    result: {
      version: string
      protocol: number
      root?: string | null
      providers?: string[]
      agents?: {
        name: string
        description?: string
      }[]
      tools?: string[]
      commands?: string[]
      permissionModes: PermissionMode[]
      defaultPermissionMode: PermissionMode
      limits?: Record<string, number>
    }
  }
  /** Stop the server, draining running turns first. */
  "server.shutdown": {
    params: {
      drainSeconds?: number
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      accepted: boolean
    }
  }
  /** Cancel the running turn (hard, or soft at the next step boundary). */
  "session.cancel": {
    params: {
      sessionId: SessionId
      turnId?: string
      mode?: "hard" | "soft"
      clearQueue?: boolean
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      cancelled: boolean
      mode: "hard" | "soft"
      cleared: number
    }
  }
  /** Release a session (refused while a turn runs unless force). */
  "session.close": {
    params: {
      sessionId: SessionId
      force?: boolean
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      closed: boolean
    }
  }
  /** Create a session and open it. */
  "session.create": {
    params: {
      name?: string
      permissionMode?: PermissionMode
      /** Another project root: the serve gateway routes the call to that root's workspace host (roadmap O-7). */
      root?: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: SessionSummary
  }
  /** Delete a session and its history. */
  "session.delete": {
    params: {
      sessionId: SessionId
      force?: boolean
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      deleted: SessionId[]
    }
  }
  /** Remove a queued prompt. */
  "session.dequeue": {
    params: {
      sessionId: SessionId
      queueId: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      dequeued: boolean
    }
  }
  /** A session's transcript as markdown, json or text. */
  "session.export": {
    params: {
      sessionId: SessionId
      format?: "markdown" | "json" | "text"
    }
    result: {
      format: "markdown" | "json" | "text"
      content: string
    }
  }
  /** Branch a session into a new one carrying its transcript. */
  "session.fork": {
    params: {
      sessionId: SessionId
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: SessionSummary
  }
  /** A session's snapshot: rows, status, queue, open questions, usage. */
  "session.get": {
    params: {
      sessionId: SessionId
    }
    result: SessionSnapshot
  }
  /** The workspace's sessions, newest activity first, paged. */
  "session.list": {
    params: {
      limit?: number
      cursor?: SessionId
      query?: string
      /** Another project root: the serve gateway routes the call to that root's workspace host (roadmap O-7). */
      root?: string
    }
    result: {
      items: SessionSummary[]
      nextCursor: string | null
    }
  }
  /** The prompts queued behind the running turn. */
  "session.queue": {
    params: {
      sessionId: SessionId
    }
    result: {
      items: QueueEntry[]
    }
  }
  /** Rename a session. */
  "session.rename": {
    params: {
      sessionId: SessionId
      name: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: SessionSummary
  }
  /** Send a prompt: start a turn, or queue / steer / interrupt the running one. */
  "session.send": {
    params: {
      sessionId: SessionId
      text: string
      delivery?: "queue" | "steer" | "interrupt"
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: Admission
  }
  /** The permission mode the session's next turns run in. */
  "session.setMode": {
    params: {
      sessionId: SessionId
      permissionMode: PermissionMode
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      permissionMode: PermissionMode
    }
  }
  /** Follow a session's events from a cursor (replay) or from a snapshot. */
  "session.subscribe": {
    params: {
      sessionId: SessionId
      afterSeq?: number
      mode?: "full" | "narration"
    }
    result: Subscription
  }
  /** Stop following a session. */
  "session.unsubscribe": {
    params: {
      sessionId: SessionId
    }
    result: {
      unsubscribed: boolean
    }
  }
  /** Effective values and where each came from, or one tier's file; secrets masked. */
  "settings.get": {
    params: {
      scope?: "effective" | "user" | "project" | "project-shared"
    }
    result: {
      scope: "effective" | "user" | "project" | "project-shared"
      /** Effective: key => {value, source, sourceLabel, sourcePath, shadowed, locked, lockReason}. A tier: the file's own object. */
      values: Record<string, unknown>
      /** Effective only: the files behind the layers, and whether each was read. */
      files?: {
        role: string
        path: string
        status: string
        note: string
      }[]
    }
  }
  /** What a save would write — the target file's diff, when each change applies, and what blocks it — without writing. */
  "settings.preview": {
    params: {
      scope?: "user" | "project" | "project-shared"
      set?: Record<string, unknown>
      unset?: string[]
      key?: string
      value?: unknown
      reset?: boolean
    }
    result: {
      scope: string
      path: string | null
      canSave: boolean
      /** key (`*` for the tier) => why the save is refused */
      refusals: Record<string, string>
      changes: ({
        key: string
        action: "set" | "reset"
        value?: unknown
        applies: string
        appliesLabel: string
      })[]
      applySummary: string
      notes: string[]
      /** The target file's JSON, before and after, as unified-diff hunks; secrets masked. */
      diff: string
    }
  }
  /** Every setting: type, default, help, apply mode, and whether a client may write it; and the tiers a save can target. */
  "settings.schema": {
    params: Record<string, unknown>
    result: {
      items: ({
        key: string
        type: string
        default?: unknown
        defaultText?: string
        group: string
        label: string
        help?: string
        enum?: unknown[]
        /** The choices a pick-one field offers (the enum, or the launch's list: themes, providers…). */
        options?: string[]
        min?: number
        max?: number
        riskClass: string
        applies: "live" | "next-turn" | "restart" | "frozen"
        appliesLabel?: string
        ui?: "easy" | "list" | "complex" | "read-only" | "hidden"
        layered?: boolean
        projectSettable?: boolean
        /** The environment variable that, when set, locks the key. */
        envVar?: string
        cliFlag?: string
        sensitive: boolean
        writableRemotely: boolean
        /** Why a client may not write the key; absent when it may. */
        remoteRefusal?: string
      })[]
      /** The tiers a save can target, and whether each can be written now. */
      tiers?: ({
        scope: "user" | "project" | "project-shared"
        label: string
        path?: string
        writable: boolean
        refusal?: string
      })[]
    }
  }
  /** Write allowlisted settings to the user tier or a trusted project's local or shared file, in one write. */
  "settings.set": {
    params: {
      key?: string
      value?: unknown
      reset?: boolean
      set?: Record<string, unknown>
      unset?: string[]
      scope?: "user" | "project" | "project-shared"
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      key?: string
      scope: string
      written: string
      applies?: string
      changed: string[]
      appliesByKey?: Record<string, string>
    }
  }
  /** A session's todo list, as its Todo tool last wrote it. */
  "todo.get": {
    params: {
      sessionId: SessionId
    }
    result: {
      items: ({
        content: string
        status: "pending" | "in_progress" | "completed" | "cancelled"
      })[]
    }
  }
  /** A finished tool call's full output, from an offset. */
  "tool.output": {
    params: {
      sessionId: SessionId
      toolCallId: string
      offset?: number
      limit?: number
    }
    result: {
      toolCallId: string
      offset: number
      content: string
      total: number
      isError: boolean
      more: boolean
    }
  }
  /** The workflows /workflow run can start. */
  "workflow.list": {
    params: Record<string, unknown>
    result: {
      available: boolean
      items: {
        name: string
      }[]
    }
  }
  /** Pause a workflow run before its next stage. */
  "workflow.pause": {
    params: {
      workflowId: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      workflowId: string
      status: "draft" | "pending" | "running" | "paused" | "resuming" | "completed" | "failed" | "cancelled"
    }
  }
  /** Resume a paused workflow run in a session. */
  "workflow.resume": {
    params: {
      sessionId: SessionId
      workflowId: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      rows: {
        role: string
        content: string
        uiOnly: boolean
      }[]
      effects: string[]
    }
  }
  /** Run a workflow in a session, as /workflow run does: it occupies the session's turn. */
  "workflow.run": {
    params: {
      sessionId: SessionId
      name: string
      /** Context values for the run; each a string, number or boolean with no whitespace. */
      vars?: Record<string, unknown>
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      rows: {
        role: string
        content: string
        uiOnly: boolean
      }[]
      effects: string[]
    }
  }
  /** The workflow runs a session's transcript holds: /workflow reports and Workflow tool calls. */
  "workflow.runs": {
    params: {
      sessionId: SessionId
    }
    result: {
      items: ({
        source: "command" | "tool"
        name: string
        status: string
        running: boolean
        workflowId?: string
        toolCallId?: string
        report?: string
      })[]
    }
  }
  /** A workflow run's status. */
  "workflow.status": {
    params: {
      workflowId: string
    }
    result: {
      workflowId: string
      status: "draft" | "pending" | "running" | "paused" | "resuming" | "completed" | "failed" | "cancelled"
    }
  }
  /** Stop a workspace host; refused while one of its turns runs, unless force. */
  "workspace.close": {
    params: {
      root: string
      force?: boolean
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      closed: boolean
    }
  }
  /** The project roots this server serves: its own, and each running workspace host. */
  "workspace.list": {
    params: Record<string, unknown>
    result: {
      items: ({
        root: string
        primary: boolean
        running: boolean
        pid?: number | null
      })[]
    }
  }
  /** Start the workspace host for another project root, or find it running. */
  "workspace.open": {
    params: {
      root: string
      /** A retry with the same key gets the original answer (5 min). */
      idempotencyKey?: string
    }
    result: {
      root: string
      primary: boolean
      running: boolean
      pid?: number | null
    }
  }
}

export type MethodName = keyof Methods
export type MethodParams<M extends MethodName> = Methods[M]['params']
export type MethodResult<M extends MethodName> = Methods[M]['result']

/** The scope each method needs. */
export const METHOD_SCOPES: { readonly [M in MethodName]: Scope } = {
  "agents.control": "write",
  "agents.list": "read",
  "agents.message": "write",
  "agents.subtree": "read",
  "agents.transcript": "read",
  "bg.inject": "write",
  "bg.list": "read",
  "bg.output": "read",
  "bg.spawn": "write",
  "bg.stop": "write",
  "client.viewing": "read",
  "command.exec": "write",
  "command.list": "read",
  "files.changed": "read",
  "files.diff": "read",
  "files.read": "read",
  "memory.add": "write",
  "memory.delete": "write",
  "memory.edit": "write",
  "memory.list": "read",
  "memory.search": "read",
  "permission.pending": "read",
  "permission.respond": "approve",
  "permission.rules": "read",
  "server.health": "read",
  "server.hello": "read",
  "server.info": "read",
  "server.shutdown": "admin",
  "session.cancel": "write",
  "session.close": "write",
  "session.create": "write",
  "session.delete": "write",
  "session.dequeue": "write",
  "session.export": "read",
  "session.fork": "write",
  "session.get": "read",
  "session.list": "read",
  "session.queue": "read",
  "session.rename": "write",
  "session.send": "write",
  "session.setMode": "write",
  "session.subscribe": "read",
  "session.unsubscribe": "read",
  "settings.get": "read",
  "settings.preview": "admin",
  "settings.schema": "read",
  "settings.set": "admin",
  "todo.get": "read",
  "tool.output": "read",
  "workflow.list": "read",
  "workflow.pause": "write",
  "workflow.resume": "write",
  "workflow.run": "write",
  "workflow.runs": "read",
  "workflow.status": "read",
  "workspace.close": "write",
  "workspace.list": "read",
  "workspace.open": "write",
}

/** The methods that accept an `idempotencyKey`. */
export const IDEMPOTENT_METHODS: readonly MethodName[] = [
  "agents.control",
  "agents.message",
  "bg.inject",
  "bg.spawn",
  "bg.stop",
  "command.exec",
  "memory.add",
  "memory.delete",
  "memory.edit",
  "permission.respond",
  "server.shutdown",
  "session.cancel",
  "session.close",
  "session.create",
  "session.delete",
  "session.dequeue",
  "session.fork",
  "session.rename",
  "session.send",
  "session.setMode",
  "settings.set",
  "workflow.pause",
  "workflow.resume",
  "workflow.run",
  "workspace.close",
  "workspace.open",
]

/** Every event type: the shape of its `data`. */
export interface Events {
  /** The reply, complete; repairs any delta a client dropped. */
  "assistant.completed": {
    messageId?: string
    ref?: number
    content: string
    reasoning?: string
    lengthStopped: boolean
    stepsTruncated: boolean
    usage?: Usage
  }
  /** Streamed reply text. */
  "assistant.delta": {
    text: string
    partId: string
    /** Byte offset into the part; a gap means a delta was dropped. */
    offset: number
  }
  /** The tail of the reply so far, at most every 2 s, for narration subscriptions. */
  "assistant.narration": {
    partId: string
    tail: string
    /** Byte offset into the part where the tail starts; the next delta continues at offset + its byte length. */
    offset?: number
  }
  /** A background session settled; bg.output reads its answer, bg.inject sends it to a session. */
  "bg.completed": BackgroundSession
  /** A background session started, or one an earlier server or TUI left running was re-adopted. */
  "bg.started": BackgroundSession
  /** A background session's status changed (running, stalled, …). */
  "bg.status": {
    bgId: string
    status: string
    previous: string
  }
  /** The history was compacted before a turn. */
  "compaction.completed": {
    kind: "llm" | "heuristic" | "truncate"
    before: number
    after: number
    savedPct?: number
  }
  /** A transcript row was added: the prompt, a notice, a summary. */
  "message.created": {
    messageId: string
    ref?: number
    role: string
    kind?: string
    content: string
    createdAt?: number
  }
  /** A question was put in an open session: permission.requested with its sessionId, for every client, following the session or not. */
  "permission.asked": {
    askId: string
    toolCallId: string
    tool: string
    arguments: Record<string, unknown>
    reason?: string
    /** `gate`, `hook:<names>`, or `tool:<name>` for a question the call puts itself (`AskUser`, `PlanExit`) */
    source?: string
    mode?: string
    options: ("once" | "always" | "reject")[]
    alwaysScope?: Record<string, string>
    /** The delegated run that asked, when a sub-agent's question was relayed; absent for the turn's own. */
    origin?: {
      agentId: string
      agentName?: string
      parentCallId?: string
    }
    sessionId: SessionId
  }
  /** A tool call is waiting for an answer (permission.respond). */
  "permission.requested": PendingAsk
  /** A question was answered or cancelled. */
  "permission.resolved": {
    askId: string
    reply?: "once" | "always" | "reject"
    note?: string
    cancelled?: boolean
  }
  /** A question of an open session was answered or cancelled (permission.resolved, for every client). */
  "permission.settled": {
    sessionId: SessionId
    askId: string
    reply?: "once" | "always" | "reject"
    cancelled?: boolean
  }
  /** Streamed reasoning text. */
  "reasoning.delta": {
    text: string
    partId: string
    /** Byte offset into the part; a gap means a delta was dropped. */
    offset: number
  }
  /** This client fell behind; ephemeral events were dropped — resubscribe. */
  "server.overflow": {
    dropped: number
    action: "resubscribe"
  }
  /** The server is stopping. */
  "server.shutdown": {
    reason: string
    graceSeconds: number
  }
  /** Liveness, every tickIntervalMs. */
  "server.tick": {
    now: number
    turnsRunning: number
  }
  /** A session was created. */
  "session.created": SessionSummary
  /** A session was deleted. */
  "session.deleted": {
    id: SessionId
  }
  /** The session became idle, busy or waiting_permission. */
  "session.status": {
    status: "idle" | "busy" | "waiting_permission"
  }
  /** A session was renamed, its mode changed, or its status changed (idle, busy, waiting_permission). */
  "session.updated": SessionSummary
  /** The session spend cap stopped the turn. */
  "spend_cap.breached": {
    calls: number
    spent: number
    cap: number
  }
  /** A delegated sub-agent finished. */
  "subagent.finished": {
    v?: number
    id: string
    op: string
    name?: string | null
    /** The delegated prompt; carried on started only. */
    task?: string | null
    seq?: number
    tail?: unknown
    tokens?: number
    cost?: number
    lines?: number
    model?: string
    context?: number
    calls?: {
      id: string
      label: string
      state: string
      at?: number
    }[]
    parentCallId?: string | null
    parentAgentId?: string | null
    description?: string
    items?: Record<string, unknown>[]
    stats?: Record<string, number>
    outcome?: unknown
    error?: string | null
    resumeId?: string | null
    transcriptLog?: string | null
    parentSessionId?: string | null
    childSessionId?: string | null
  }
  /** A delegated sub-agent made progress. */
  "subagent.progress": {
    v?: number
    id: string
    op: string
    name?: string | null
    /** The delegated prompt; carried on started only. */
    task?: string | null
    seq?: number
    tail?: unknown
    tokens?: number
    cost?: number
    lines?: number
    model?: string
    context?: number
    calls?: {
      id: string
      label: string
      state: string
      at?: number
    }[]
    parentCallId?: string | null
    parentAgentId?: string | null
    description?: string
    items?: Record<string, unknown>[]
    stats?: Record<string, number>
    outcome?: unknown
    error?: string | null
    resumeId?: string | null
    transcriptLog?: string | null
    parentSessionId?: string | null
    childSessionId?: string | null
  }
  /** A delegated sub-agent started. */
  "subagent.started": {
    v?: number
    id: string
    op: string
    name?: string | null
    /** The delegated prompt; carried on started only. */
    task?: string | null
    seq?: number
    tail?: unknown
    tokens?: number
    cost?: number
    lines?: number
    model?: string
    context?: number
    calls?: {
      id: string
      label: string
      state: string
      at?: number
    }[]
    parentCallId?: string | null
    parentAgentId?: string | null
    description?: string
    items?: Record<string, unknown>[]
    stats?: Record<string, number>
    outcome?: unknown
    error?: string | null
    resumeId?: string | null
    transcriptLog?: string | null
    parentSessionId?: string | null
    childSessionId?: string | null
  }
  /** A Todo call rewrote the session's todo list; carries the whole list. */
  "todo.updated": {
    toolCallId?: string
    items: ({
      content: string
      status: "pending" | "in_progress" | "completed" | "cancelled"
    })[]
  }
  /** A tool call finished (content capped; tool.output has the rest). */
  "tool.finished": {
    messageId?: string
    ref?: number
    toolCallId: string
    name: string
    isError: boolean
    durationMs?: number
    /** At most 256 KiB; tool.output reads the rest. */
    content: string
    truncated?: boolean
    diff?: string
    denial?: {
      kind: string
      reason?: string
    }
    replaces?: string
  }
  /** A tool call started. */
  "tool.started": {
    messageId?: string
    ref?: number
    toolCallId: string
    name: string
    arguments?: Record<string, unknown>
  }
  /** A turn ended, with its stopReason. */
  "turn.completed": {
    stopReason: "end_turn" | "max_steps" | "length" | "cancelled" | "spend_cap" | "error"
    error?: string
    messageId?: string
  }
  /** A queued prompt left the queue (sent or removed). */
  "turn.dequeued": {
    queueId: string
    text?: string
    reason: "sent" | "removed"
  }
  /** A prompt was queued behind the running turn. */
  "turn.queued": {
    queueId: string
    text: string
    position: number
  }
  /** A turn began. */
  "turn.started": {
    turnId: string
    messageId?: string
  }
  /** A steering message was handed to the running turn. */
  "turn.steered": {
    turnId?: string
    steerId: string
  }
  /** The running turn reached a step boundary. */
  "turn.step": {
    step: number
    maxSteps: number
    context?: Record<string, unknown> | null
  }
  /** Token and cost usage changed. */
  "usage.updated": {
    step: number
    usage?: Usage | null
    turnUsage?: Usage | null
  }
}

export type EventName = keyof Events

/** Whether each event type is durable (logged, carries a `seq`) and its scope. */
export const EVENT_KINDS: { readonly [E in EventName]: { readonly durable: boolean; readonly scope: 'session' | 'server' } } = {
  "assistant.completed": { durable: true, scope: "session" },
  "assistant.delta": { durable: false, scope: "session" },
  "assistant.narration": { durable: false, scope: "session" },
  "bg.completed": { durable: false, scope: "server" },
  "bg.started": { durable: false, scope: "server" },
  "bg.status": { durable: false, scope: "server" },
  "compaction.completed": { durable: true, scope: "session" },
  "message.created": { durable: true, scope: "session" },
  "permission.asked": { durable: false, scope: "server" },
  "permission.requested": { durable: true, scope: "session" },
  "permission.resolved": { durable: true, scope: "session" },
  "permission.settled": { durable: false, scope: "server" },
  "reasoning.delta": { durable: false, scope: "session" },
  "server.overflow": { durable: false, scope: "server" },
  "server.shutdown": { durable: false, scope: "server" },
  "server.tick": { durable: false, scope: "server" },
  "session.created": { durable: false, scope: "server" },
  "session.deleted": { durable: false, scope: "server" },
  "session.status": { durable: true, scope: "session" },
  "session.updated": { durable: false, scope: "server" },
  "spend_cap.breached": { durable: true, scope: "session" },
  "subagent.finished": { durable: true, scope: "session" },
  "subagent.progress": { durable: false, scope: "session" },
  "subagent.started": { durable: true, scope: "session" },
  "todo.updated": { durable: true, scope: "session" },
  "tool.finished": { durable: true, scope: "session" },
  "tool.started": { durable: true, scope: "session" },
  "turn.completed": { durable: true, scope: "session" },
  "turn.dequeued": { durable: true, scope: "session" },
  "turn.queued": { durable: true, scope: "session" },
  "turn.started": { durable: true, scope: "session" },
  "turn.steered": { durable: true, scope: "session" },
  "turn.step": { durable: false, scope: "session" },
  "usage.updated": { durable: true, scope: "session" },
}
